name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339276916511:role/oidc_role
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
        working-directory: terraform